Version bump to 1.7.0 for Release
microsoft/kafka-connect-cosmosdb pull request #501
Opened 2023-03-17 22:46 UTC by aayush3011

## Type of PR

- [ ] Documentation changes
- [ ] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR

## Observability + Testing
- What changes or considerations did you make in relation to observability?

- Did you add testing to account for any new or changed work?

## Review notes

## Issues Closed or Referenced

- Closes #<issue number> (this will automatically close the issue when the PR closes)
- References #<issue number> (this references the issue but does not close with PR)

2023-03-17 22:50 UTC, FabianMeiswinkel approved these changes
LGTM

2023-03-17 22:59 UTC, xinlian12 commented on CHANGELOG.md
> +* Updated `azure-cosmos` version to 4.41.0.
should we upgrade to 4.42.0? it released this morning

2023-03-17 23:00 UTC, xinlian12 approved these changes
LGTM, thanks

2023-03-17 23:01 UTC, kushagraThapar requested changes

2023-03-17 23:01 UTC, kushagraThapar commented on CHANGELOG.md
> +### 1.7.0
Missing date here

2023-03-17 23:01 UTC, kushagraThapar commented on doc/README_Sink.md
> +| value.converter | string  | Serialization format for the value data written into the Kafka topic                                                                                         | Required |
@xinlian12 this looks like a new feature / fix. I don't see it in the changelog. Can you please check?

2023-03-17 23:03 UTC, kushagraThapar commented on doc/README_Sink.md
> +| value.converter | string  | Serialization format for the value data written into the Kafka topic                                                                                         | Required |
nvm, ignore my above comment.

2023-03-17 23:03 UTC, kushagraThapar approved these changes
@aayush3011 please add the date to release changelog. otherwise looks good to me, thanks!

2023-03-18 00:19 UTC, xinlian12 commented on CHANGELOG.md
> +* Updated `azure-cosmos` version to 4.41.0.
Discussed offline, keep 4.41.0

2023-03-18 00:20 UTC, xinlian12 approved these changes
LGTM, thanks

2023-03-18 01:03 UTC, kushagraThapar approved these changes

2023-03-18 01:08 UTC, merged